### ISSUE TITLE
structure of edges yamls

### ISSUE THREAD

**Issue by richardjgowers** [openforcefield/protein-ligand-benchmark#92]
Currently the [edges yaml](https://github.com/openforcefield/protein-ligand-benchmark/blob/main/data/hif2a/03_edges/01_perses_openfe.yml) is structured as
```
mapper: <mapper algorithm>
planner: <planner algorithm>
edges:
  <name>:
    ligand_a: <a_name>
    ligand_b: <b_name>
    atom_mapping: <mapping dict>
    score: <score>
```

IMO The mapper isn't a per-network property but instead a per-edge property.  Also arbitrary remarks would also be useful (e.g. annotating that a certain edge was hand tweaked and why).
```
planner: <planner algorithm>
remarks: <freeform description of this network>
edges:
  <name>:
    ligand_a: <a_name>
    ligand_b: <b_name>
    atom_mapping: <mapping dict>
    score: <score>
    mapper: <mapper>
    remarks: <freeform remarks>
```

**Comment by dfhahn** [comment]
I like the suggestion. Maybe you want to be more specific about the score to accommodate for various different scores? E.g., 
```
score:
    lomap: <lomap_score>
    shape_sim: <shape similarity>
    …
```
